### ISSUE TITLE
Extend TDequeConcurrent

### ISSUE THREAD

**Issue by JBSchueler** [Pixinn/misc#2]
Hi,

Currently I am using a library [(ESP32DMASPI)](https://github.com/hideakitai/ESP32DMASPI) which uses the deque library but I ran into issues.
After analyzing I found the root cause is the deque.

Therefor I would like to make thread save and found this repository.

I really like tis solution because I don't have to modify the library code that much.
The only thing to do is to extend the feature list to be more compatible with deque.
So for so good.

The problem I am facing now is how to implement `.back()` and `.front()`
I am not that familiar with writing templates and pointers.

[branch extend deque fuctions](https://github.com/JBSchueler/thread_safe_deque/tree/feature/1_extend_deque_functions)

**Comment by JBSchueler** [comment]
Changes to ESP32DMASPI (slave) are

```c
//#include <deque>
#include "TDequeConcurrent.h"
```
...

```c
//    std::deque<spi_slave_transaction_t> transactions;
//    std::deque<uint32_t> results;
    TDequeConcurrent<spi_slave_transaction_t> transactions;
    TDequeConcurrent<uint32_t> results;
```

So the library is more or less the same as the original one of ESP32DMASPI.

The problem/error I get is.

```
In file included from C:\projects\Arduino\slave_simple_task_test8\slave_simple_task_test8.ino:1:
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h: In member function 'bool arduino::esp32::spi::dma::Slave::wait(uint8_t*, const uint8_t*, size_t)':
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:109:67: error: taking address of temporary [-fpermissive]
         esp_err_t e = spi_slave_transmit(host, &transactions.back(), portMAX_DELAY);
                                                                   ^
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h: In member function 'bool arduino::esp32::spi::dma::Slave::queue(uint8_t*, const uint8_t*, size_t)':
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:132:70: error: taking address of temporary [-fpermissive]
         esp_err_t e = spi_slave_queue_trans(host, &transactions.back(), portMAX_DELAY);
                                                                      ^
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h: In member function 'void arduino::esp32::spi::dma::Slave::addTransaction(uint8_t*, const uint8_t*, size_t)':
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:217:42: error: using temporary as lvalue [-fpermissive]
         transactions.back().length = 8 * size;  // in bit size
                                          ^~~~
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:218:41: error: using temporary as lvalue [-fpermissive]
         transactions.back().tx_buffer = tx_buf;
                                         ^~~~~~
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:219:41: error: using temporary as lvalue [-fpermissive]
         transactions.back().rx_buffer = rx_buf;
                                         ^~~~~~
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:220:43: error: using temporary as lvalue [-fpermissive]
         transactions.back().user = (void*)this;
                                           ^~~~
In file included from C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:9,
                 from C:\projects\Arduino\slave_simple_task_test8\slave_simple_task_test8.ino:1:
C:\projects\Arduino\libraries\ESP32DMASPI/TDequeConcurrent.h: In instantiation of 'T TDequeConcurrent<T>::back() [with T = spi_slave_transaction_t]':
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:109:67:   required from here
C:\projects\Arduino\libraries\ESP32DMASPI/TDequeConcurrent.h:119:34: error: could not convert '&((TDequeConcurrent<spi_slave_transaction_t>*)this)->TDequeConcurrent<spi_slave_transaction_t>::_collection.std::deque<spi_slave_transaction_t, std::allocator<spi_slave_transaction_t> >::back()' from '__gnu_cxx::__alloc_traits<std::allocator<spi_slave_transaction_t>, spi_slave_transaction_t>::value_type*' {aka 'spi_slave_transaction_t*'} to 'spi_slave_transaction_t'
         return &_collection.back();
                                  ^
C:\projects\Arduino\libraries\ESP32DMASPI/TDequeConcurrent.h: In instantiation of 'T TDequeConcurrent<T>::front() [with T = unsigned int]':
C:\projects\Arduino\libraries\ESP32DMASPI/ESP32DMASPISlave.h:165:38:   required from here
C:\projects\Arduino\libraries\ESP32DMASPI/TDequeConcurrent.h:82:35: error: invalid conversion from '__gnu_cxx::__alloc_traits<std::allocator<unsigned int>, unsigned int>::value_type*' {aka 'unsigned int*'} to 'unsigned int' [-fpermissive]
         return &_collection.front();
                                   ^
```

Somehow I have to pass `_collection.back()` (`and _collection.front()`) in the right way, and how I currently did it isn't.

How can I solve this?

**Comment by Pixinn** [comment]
Hi,
There are multiple errors here. I can't see the calling code so my view is incomplete, but here is what I can infer about those errors:

1. You are giving the address of a temporary value to _spi_slave_queue_trans()_. If you want to use this syntax, _back()_ has to return a reference to the element in the queue (**T&**)
2. Same here: _transactions.back().length = 8 * size_ ; if you want modify an element of the queue, _back()_ has to return a reference to it

Multiples errors are the same as 1 & 2

The template errors are more difficult to read. But I assume it is because _back()_ (and _front()_) are defined to return a T (a **copy** of the element in the queue) but you actually return a **pointer**:  _return &_collection.back();_

Once again that should be cleared if you return a reference to it:

```C++
 T& back( void ) noexcept
{
/* ... */
 return _collection.back();
}
```

Do the same with _front()_.

Reading the rest of your code, I think you misused the condition variables in _size()_ and _empty()_ as they will block until data is added to the queue.

As stated in the README.md, this code is illustrating [an article of my blog](https://www.xtof.info/c11-concurrency-wrapping-stdlist-to-make-it-thread-safe.html) that you can read for more info.

**Comment by Pixinn** [comment]
As this is not an issue concerning my code, I close this issue. Feel free to DM me on social networks for further info.

**Comment by JBSchueler** [comment]
@Pixinn , I really appreciated you replied that fast.
No it is not concerning your code.
Although it could have a benefit to have more features ;)

Thanks a lot, will continue to complete my code!
